name: awx
version: 0.0.3
appVersion: 6.0.0
apiVersion: v1
description: AWX provides a web-based user interface, REST API, and task engine built on top of Ansible.
keywords:
  - Ansible AWX
  - Automation configuration deployment
  - Devops
  - Web-based GUI
home: https://github.com/ansible/awx
icon: https://www.ansible.com/hubfs/2017_Images/BrandPage/Brand-Assets/Tower/Ansible_RH_AnsibleTower_RGB_RedWhite.svg?t=1528996684045
sources:
  - https://github.com/rhythmictech/helm-charts/tree/master/charts/awx
maintainers:
  - name: Steven Black
    email: steven.black@rhythmictech.com
engine: gotpl
